### ISSUE TITLE
Add position of cursor

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-ast-viewer#1]
It would be useful to say what pos the cursor is currently at.

**Comment by cancerberoSgx** [comment]
I think you need to register a Language Service Plugin in order to do this. And even so, LS will only update the pos (or range if selection) at certain particular moments. (completion, refactor suggestions). And I don't think you can register a plugin programmatic ally ... 

Would be interesting to investigate the possibility of something like polling - if you detect insertions probably that means the user is writing... but not sure.. On the other hand would be easy to screw the performance doing polling so be careful. Not sure if that should be responsibility of this library though... thinking... .

my two cents...

**Comment by dsherret** [comment]
For this it's just getting the position of the cursor in the textbox from ace editor.
