### ISSUE TITLE
Repo becomes too large

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-ast-viewer#124]
The repo is way too large. I'm going to manually delete some commits on the release, but we should find a way to make it smaller. Just downloaded like 1.35 gigs doing a git pull.

**Comment by Gerrit0** [comment]
Simplest way to do this is to add `single-commit: true` to the publish step so that the branch gets force pushed each build. It'll still grow local clones, but much much much more slowly. I'm using this on TypeDoc's site now as I ran into a similar problem..

The better option is probably to use https://github.com/actions/deploy-pages, which makes it possible to deploy without pushing to a branch at all... I haven't played with this yet as the single-commit has been good enough for me.

**Comment by dsherret** [comment]
@Gerrit0 thanks! That seems like a good option. I will enable that (too lazy to switch it to the deploy-pages action lol)
