### ISSUE TITLE
Web site's code editor is broken

### ISSUE THREAD

**Issue by sandersn** [dsherret/ts-ast-viewer#25]
Not sure this is the right place to report this, but I get this error on ts-ast-viewer.com:

Error loading code editor. Please refresh the page to try again.

**Comment by dsherret** [comment]
Hey Nathan! Yup this is the place to report this.

Try doing a hard refresh (ctrl+f5) a few times. If that doesn't work, does it work in an incognito window? The site previously used service workers because of *create-react-app*, but I ran into a few weird behaviour issues like the one you mentioned so I disabled them (I investigated a bit online, but couldn't find much information about how to fix the issue). Anyway, going forward it should work for you after doing that, but let me know if not.

Side note: This problem should only happen to people who previously visited the website while service workers were enabled. I thought the unregistration of service workers would cause this issue to not happen, but I guess not.

**Comment by sandersn** [comment]
Well, I just tried this morning and everything is fine again. I guess that was long enough to invalidate some cache in Chrome? Anyway, thanks for the explanation!

**Comment by dsherret** [comment]
Yeah maybe so. I disabled the service workers a few weeks ago so I guess they kept caching the site locally for a long time. Hopefully it won't be an issue going forward.

By the way, if you think of any improvements with the site that would help you then let me know. I'd be glad to implement it!
