### ISSUE TITLE
ts-creator returns synthetic node with (pos, end) as (-1, -1)

### ISSUE THREAD

**Issue by octref** [dsherret/ts-ast-viewer#43]
Hey @dsherret and @kingwl, thanks a lot for creating ts-ast-viewer and ts-creator. Super helpful for my current work now.

I noticed that the created synthetic nodes all have (pos, end) as (-1, -1). The only way I can get correct positioning is to use `ts.createPrinter` to print the AST and then use `ts.createSourceFile` to re-create the source file. Are any of you aware of any way to create virtual SourceFile by building up AST, while still maintaining correct position for each nodes?

Thanks in advance!

**Comment by Kingwl** [comment]
Thanks for the affirmation of my work.
ts-creator is only a transformer that map ast to a factory.
That is a little hard to resolve the correct position based on the current codebase, But it is not impossible.
I think we can rewrite the emitter (maybe only need to rewrite a small part), locally and recursively  calculate the correct position? 

Just an idea, need to research and try it out, hope this helps😬

**Comment by dsherret** [comment]
Hey @octref, that's by design—the nodes created with the factory functions won't have any positions associated with them. The printer is what determines the final text and I'm sure it would be very complicated for the TypeScript team to keep the printer and factory functions in sync for their positions.

Additionally, it would require a lot of extra work to keep the node positions up to date. For example, say you insert a statement at the start of the file... well now you have to traverse the ancestor nodes and following nodes in the file to update all their positions. I guess what could be done is for a utility to be made that traverses the AST once you're done manipulating it and it would set the node positions... that would be a lot of work though and hard to keep it up to date with the printer.

Also, thanks @Kingwl for creating ts-creator! It was recommended in #40 and is very useful. I have a link to it in the options menu.

**Comment by dsherret** [comment]
By the way, what you are doing by printing and then parsing the text to create a new AST is probably the most reliable/easiest way for doing this... but yeah it will be a little slower than a utility that would traverse the AST to set the correct positions.

**Comment by octref** [comment]
Thanks, I'll close the issue then.

One note is that if `ts.IScriptSnapshot` seems to offer a way to update a range with next text, so efficiency wise this seems like a better way to update the AST (only need to print the specific nodes and attach them).
