### ISSUE TITLE
A user guide for the project

### ISSUE THREAD

**Issue by izosak** [dsherret/ts-ast-viewer#44]
Hi @dsherret!

First, thank you very much for the time and effort you have dedicated to the ts-ast-viewer project; I find it very useful as a student.

Second, may I ask if there is a guide for using the project locally and not through the website? I tried importing it to Visual Studio, but unfortunately many modules and other identifiers are not recognized by the IDE.

I should mention that I am completely new to TS (and JS accordingly) and therefore I'm a bit clueless regarding the installation and usage of the project on my computer.

Any help would be much appreciated! :)

**Comment by dsherret** [comment]
Hey @izosak, sorry I completely missed this message! I apologize about that.

I'll add a user guide soon. Basically, use visual studio code instead of visual studio (I know, as a c# dev I love visual studio too, but it doesn't work great for this or most typescript projects).

1. Run `yarn install`
2. Run `yarn start` <-- this will launch a local development web server and open a browser window with the website. When you save a file it should refresh the website within a few seconds.

**Comment by izosak** [comment]
Thanks @dsherret, that's very kind of you!

**Comment by dsherret** [comment]
No problem!

Updated the readme.md file. Let me know if there's anything else you'd like me to add.
