### ISSUE TITLE
Node has wrong kind

### ISSUE THREAD

**Issue by nicolasnobelis** [dsherret/ts-ast-viewer#54]
Hello !

I have the following TS :
export interface IChecklistVersionPeriodPicker extends IChecklistVersion {
    type : ChecklistVersionType.period
}

The AST viewer reports as PropertySignature with kind 154

However my program reports it as PropertySignature with kind 153.
Looking at the sources, kind 154 is PropertyDeclaration...

Thanks in advance and sorry if it has already been reported.

Best regards
Nicolas

**Comment by dsherret** [comment]
Hey @nicolasnobelis, this is because the compiler api uses an enum internally for the kind value (`ts.SyntaxKind`) and as more members are added to that enum between compiler versions the values will change.

If you go to the "Options" menu in the top and change the version to use the same version of the compiler that your program is using then the values will be the same.

**Comment by nicolasnobelis** [comment]
Hello David !

Thanks for the thorough explanation.
Indeed it was a version mismatch. I will, as you advised, protect my code by using the SyntaxKind,
